### ISSUE TITLE
Missing Intents

### ISSUE THREAD

**Issue by xTr07a** [Falyrion/Loot-Bot#2]
The Bot can't login because intents are missing.

**Comment by Falyrion** [comment]
Can you specify this further? I get no errors with the code.

**Comment by AlexandrePereiraDaCosta** [comment]
Think I have a similar error, when running "docker run -it twitch_prime_bot", the terminal display the following error:

Traceback (most recent call last):
  File "//discord_bot.py", line 55, in <module>
    client = TwitchLootBot()
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by Falyrion** [comment]
I see the problem. Running the bot without docker works fine, but Intents are needed with docker. That's some change in the API that happened. 

To solve some Intents have to be added to line 55 in [`/bot/discord_bot.py`](https://github.com/Falyrion/Loot-Bot/blob/main/bot/discord_bot.py) and also to the application settings of the bot on the discord developer website. It goes something like this:

```python
client = TwitchLootBot(intents=discord.Intents().all())
```

I have not yet had the time to figure it out and fix the problem. The bot should also not need all intents, only read-chat and write-chat.

**Comment by riggerbh** [comment]
The file "discord_bot.py" in the Folder "Loot-Bot-Main/bot" 

I changed this (start line 55 at the bottom):

    client = TwitchLootBot()
    client.run(TOKEN)

To this:

    intents = discord.Intents.default()
    intents.message_content = True

    client = TwitchLootBot(intents=intents)

    client.run(TOKEN)

It's running for me. I had to set the Privileged Gateway Intents to "ON" in the Discord applications for the bot before I ran this.

**Comment by Falyrion** [comment]
Maintenance of this project is currently on halt. Many web scraping methods might no longer work due to changes in the target websites. Furthermore, discord.py is no longer maintained by its developers, therefor a rewrite of this project using pycord would be necessary.
